@startuml
class HomePage {
  + render(): JSX.Element
}

class SearchBar{
    + contract: string[]
  + priceOptionsBuy: number[]
  + priceOptionsRent: number[]
  - query: object
  - suggestions: string[]
  - navigate: function
  + switchType(val: string): void
  + getCityCoordinates(location: string): object
  + handleSearch(event: Event): void
  + handleChange(event: Event): void
  + handleSelectSuggestion(city: string): void
  + handlePriceChange(event: Event): void

}

HomePage --> SearchBar : "Contiene"


@enduml
