@startuml
package Boundary{

class ProfilePage {
  - agencyInfo: object
  - avatar: string
  - isAdminOpen: boolean
  - isAgentOpen: boolean
  - isEditAgencyOpen: boolean
  - isChangePasswordOpen: boolean
  + handleLogout(): void
  + openPasswordChange(): void
  + closePasswordChange(): void
  + openAdminDialog(): void
  + closeAdminDialog(): void
  + openAgentDialog(): void
  + closeAgentDialog(): void
  + openEditAgencyDialog(): void
  + closeEditAgencyDialog(): void
  + updateAvatar(avatar: string): void
  + fetchSavedProperties(pageParam: number): object
  + fetchUploadedProperties(pageParam: number): object
  + render(): JSX.Element
}


class ChangePassword {
  - oldPassword: string
  - newPassword: string
  - confirmPassword: string
  - error: string
  - successMessage: string
  + handleSubmit(event: object): void
  + handleClose(): void
  + render(): JSX.Element
}

ProfilePage --> ChangePassword
}

package UserController {
class UserController {
    + addAdmin(req, res)
    + addAgency(req, res)
    + addAgent(req, res)
    + getAgents(req, res)
    + getAdmins(req, res)
    + getAgencies(req, res)
    + deleteAdmin(req, res)
    + deleteAgency(req, res)
}
}
package Entity{
entity User {
  * id : Int
  * email : String
  * username : String
  * passwordHash : String
  * role : String
  - avatar : String?
  * createdAt : DateTime
}

}
ProfilePage --> UserController
UserController --> User
@enduml
